// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oMediaCenter.MetaDatabase;

namespace oMediaCenter.MetaDatabase.Migrations
{
    [DbContext(typeof(MetaDataContext))]
    [Migration("20180923130741_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("oMediaCenter.MetaDatabase.MediaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OriginalString");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("MediaDatum");
                });
#pragma warning restore 612, 618
        }
    }
}
