// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oMediaCenter.Web.Model;

#nullable disable

namespace oMediaCenter.Web.Migrations
{
    [DbContext(typeof(MediaCenterContext))]
    [Migration("20250510182144_AddedLastPlayedDate")]
    partial class AddedLastPlayedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("oMediaCenter.Web.Model.FilePosition", b =>
                {
                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("LastPlayedPosition")
                        .HasColumnType("TEXT");

                    b.HasKey("FileHash");

                    b.ToTable("FilePositions");
                });
#pragma warning restore 612, 618
        }
    }
}
