// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oMediaCenter.Web.Model;

#nullable disable

namespace oMediaCenter.Web.Migrations
{
    [DbContext(typeof(MediaCenterContext))]
    [Migration("20260321084050_CachedMediaInformation")]
    partial class CachedMediaInformation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("oMediaCenter.Web.Model.CachedMediaInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Episode")
                        .HasColumnType("text");

                    b.Property<string>("Filename")
                        .HasColumnType("text");

                    b.Property<string>("Genres")
                        .HasColumnType("text");

                    b.Property<string>("ImdbNumber")
                        .HasColumnType("text");

                    b.Property<string>("OtherInfo")
                        .HasColumnType("text");

                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("VideoType")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Filename")
                        .IsUnique();

                    b.ToTable("CachedMediaInformationRecords");
                });

            modelBuilder.Entity("oMediaCenter.Web.Model.FilePosition", b =>
                {
                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("LastPlayedPosition")
                        .HasColumnType("TEXT");

                    b.HasKey("FileHash");

                    b.ToTable("FilePositions");
                });
#pragma warning restore 612, 618
        }
    }
}
